config/routes.rb
Summerreading::Application.routes.draw do
  resources :courses
  post 'courses/action'
  post 'courses/main'

  
  root :to => 'courses#index'
  
  match 'courses/:name/:id' => 'courses#show', :as => 'courses'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :course
  has_many :novels, :dependent => :destroy
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :categories, :dependent => :destroy
end

app/models/novel.rb
class Novel < ActiveRecord::Base
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :clear_course
  
  def clear_course
    cookies.permanent[:course] = nil
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  def index
    @courses = Course.all
    
    if cookies[:course]
      course = Course.find_by_name(cookies[:course])
      redirect_to courses_url(:name => course.name.parameterize, :id => course.id) if course
    end
  end

  # GET /courses/1
  def show
    @course = Course.find(params[:id])
    cookies.permanent[:course] = @course.name

    respond_to do |format|
      format.html # show.html.erb
    end
  end
  
  def main
    clear_course
    redirect_to root_url
  end
  
  def action
    if cookies[:novels].blank?
      novel = {
        params[:name].to_s => {
          :page => params[:page].to_s,
          :read => params[:read]
        }
      }
      cookies.permanent[:novels] = JSON.generate(novel)
    else
      novel = {
        params[:name].to_s => {
          :page => params[:page].to_s,
          :read => params[:read]
        }
      }
      
      cookies.permanent[:novels] = JSON.generate(JSON.parse(cookies[:novels]).merge!(novel))
    end
    
    @read = params[:read]
    @name = params[:name]
    
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
  def novel_info(name)
    return {:read => false, :page => ''} if cookies[:novels].blank?
    novels = JSON.parse(cookies[:novels])
    
    if novels[name].blank?
      {:read => false, :page => ''}
    else
      {:read => novels[name]['read'], :page => novels[name]['page']}
    end
  end
end

app/views/courses/_actions.html.erb
<%= form_tag(courses_action_path, :remote => true) do %>
  <%= hidden_field_tag :name, name %>
  <p>
    <%= label_tag :page, 'Page:' %>
    <%= text_field_tag :page, page, :disabled => active %>
  </p>
  <p>
    <%= label_tag :read, 'Read?' %>
    <% if active %>
      <%= check_box_tag :read, '', :checked => 'checked' %>
    <% else %>
      <%= check_box_tag :read %>
    <% end %>
  </p>
<% end %>

app/views/courses/action.js.erb
var note = $("li:contains('<%= @name %>')").next('.notes')
var input = $("input[type=text]", note);

if ('<%= @read %>' == '1') {
  input.attr('disabled', 'true');
  $("li:contains('<%= @name %>')").css('text-decoration', 'line-through');
} else {
  input.removeAttr('disabled');
  $("li:contains('<%= @name %>')").css('text-decoration', 'none');
}

app/views/courses/index.html.erb
<h1>Choose your class</h1>

<div id="classes">
  <% for course in @courses %>
    <div class="class"><%= link_to course.name, courses_path(:name => course.name.parameterize, :id => course.id) %></div>
  <% end %>
</div>

app/views/courses/show.html.erb
<h1>Summer Reading List</h1>

<div id="classes">
  <p><%= link_to'← All courses', courses_main_path, :class => 'all', :method => :post %></p>
  <% for category in @course.categories %>
    <div class="class desc"><%= category.name %></div>
    <div class="novels">
      <ul>
        <% for novel in category.novels %>
        <div class="novel">
          <% if novel_info(novel.name)[:read] %>
            <li style="text-decoration:line-through;"><%= novel.name %></li>
          <% else %>
            <li><%= novel.name %></li>
          <% end %>
          <div class="notes">
            <%= render 'actions', :name => novel.name, :page => novel_info(novel.name)[:page], :active => novel_info(novel.name)[:read] %>
          </div>
          
          <%= raw "<hr/>" if novel.id != category.novels[category.novels.count-1].id %>
        </div>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Summer Reading</title>
  <link href='http://fonts.googleapis.com/css?family=Lobster|Droid+Sans|Droid+Serif' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application" %>
  <noscript>
    <style type="text/css">
      div.notes {
        display: block;
      }
    </style>
  </noscript>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<div id="content">

  <%= yield %>
  
  <div id="footer">
    <p>Copyright &copy; 2011, Rishi Shah.</p>
  </div>

</div>
</body>

</html>